name: Run Cypress In Docker
on: [push]
jobs:
  Cpyress-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
        node-version: 16.x
        cache: 'npm'
      - run: yarn install
      - run: yarn cypress:docker
