name: Run Cypress In Docker
on: [push]

env:
  CYPRESS_USER: quality+andy.hohenner@konghq.com
  # CYPRESS_PASSWORD: in Github UI secrets

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_USER: quality+andy.hohenner@konghq.com
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-results.xml